### PR TITLE
Assesdevelop

### PR DESCRIPTION
**Pull request by dallintine**
## Description
this the new angular frame work that contain the eslint and airbnb 

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ifeLight — COMMENTED** [review]
You did not added some angular files like the angular.json file

**Comment by ifeLight** [comment]
I can see they now pass the test

**Comment by dave-ok** [comment]
@ifeLight The tests are passing because majority of the code has been commented out or the rules have been bypassed. This is not really recommended practice. I'm surprised this passed on Codacy because inline rule bypasses aren't usually approved

**Comment by syntiara** [comment]
Hi guys, I see this is referring to Eslint and Airbnb, do we still need this PR to be merged in?

**Review by nully0x — APPROVED** [review]

**Comment by dave-ok** [comment]
@ifeLight I this PR should be closed as it has been addressed in a separate PR

**Comment by ifeLight** [comment]
This issue has already been solved in a previously approved PR, and it has a conflict with the base branch, so am closing this PR

**Pull request closed without merging**
