### PR TITLE
[chore] - Install angular framework

### LINKED ISSUE #8: [chore]: Install/setup angular framework
### Install angular framework and prettier
Setup initial angular codebase and code formatting with prettier. Use default TSLint for angular

### Acceptance Criteria
- [ ] 1. Install angular framework
- [ ] 2. Install and configure prettier
- [ ] 3. Pass Codacy tests

### PR DESCRIPTION
**Pull request by ArinzeOkorji**
## Description
Installed the angular framework for the project's frontend.

Dependencies that are required include:
"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.23",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "prettier": "^2.0.5",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "tslint-config-prettier": "^1.18.0",
    "tslint-plugin-prettier": "^2.3.0",
    "typescript": "~3.5.3"
  }

Fixes #8 

## How Has This Been Tested?
Tested the project by running `ng-build` and `ng build --prod`.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by syntiara — APPROVED** [review]

**Comment by dave-ok** [comment]
@ArinzeOkorji You have named the branch properly. But I think the PR can have a more descriptive title other than "Ch-install-angular-framework". Maybe you should edit the title to free text like "[chore] - Install angular framework". @syntiara What do you think?

**Review by dave-ok — APPROVED** [review]

**Comment by syntiara** [comment]
Yeah @dave-ok that sounds good. If @ArinzeOkorji  agrees to it, he can also change the commit messages as well as make an edit to the PR template to answer questions relating to this particular PR

**Review by ifeLight — APPROVED** [review]
Okay we can move on

**Comment by dallintine** [comment]
good to go

**Pull request merged**
