### PR TITLE
[Feature] reporter authentication

### LINKED ISSUE #14: [FEATURE] Create a login page
As a user, I want to login with a verified Facebook/google account.

**Describe the solution you'd like**

**Criteria: Acceptance criteria:** A login page

**Scenario:** Given a registered person visits our platform when he/she clicks the Reporters button on the landing page and gets routed to the signup page and clicks the Already got an account? Login link, he/she then gets routed to the login page.

### PR DESCRIPTION
**Pull request by ArinzeOkorji**
## Description
Summary of the change and relevant motivation and context. 
This feature enables reporters to login to the platform using social authentication.

Dependencies that are required for this change include:
"@angular/fire": "^5.2.1",
"firebase": "^7.14.4",

Fixes #14 

## How Has This Been Tested?
Tested code by writing isolated unit tests that ensured methods were being called in both services and components.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code documentation
- [x ] I have added tests that prove my fix is effective and that this feature works
- [ x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ifeLight — DISMISSED** [review]

**Review by dave-ok — COMMENTED** [review]
@ArinzeOkorji This is cool. When I click login with google it does not return to the dashboard as intended. Is there something I am doing wrong? Or this still a work in progress?

**Review by ifeLight — DISMISSED** [review]

**Review by dave-ok — DISMISSED** [review]
@ArinzeOkorji Nice work! I see you used the `onAuthStateChanged` for detecting signOuts only, while you used `getRedirectResults` for detecting auth state after returning from a redirect. This is very good, although `onAuthStateChanged` would've sufficed, the `getRedirectResults` gives more info and is ideal in situations where you want to catch/detect and handle various auth errors.

The drawback of `getRedirectResults`, however, is that it does not return immediately on page redirect but `onAuthStateChanged` does. And for this reason you added a spinner. Neat trick! But in the current state, the flicker of the login page can be a bit confusing. One suggestion though is that instead of a small spinner, hide the login page/buttons and use something that covers the entire page, maybe also with a bigger spinner and a message saying something like "Attempting to log you in...".  I will approve this PR but maybe you could look into these suggestions in a follow up PR? Thanks!

**Comment by ArinzeOkorji** [comment]
@dave-ok Thanks for the feedback! I like the idea of using something that covers the entire page, maybe also with a bigger spinner and a message saying something like "Attempting to log you in...". Would implement that

**Comment by dave-ok** [comment]
@ArinzeOkorji Looking good. But I failed to mention that I noticed that it seems that this current branch `ft-reporter-authentication` was created off your first branch `ft-reporter-dashboard` and as a result, all those commits propagated to this branch leading to 35 commits in total. I don't know if this was intentional since the `ft-reporter-dashboard` hasn't been merged yet and maybe you have functionality that you need there. Either way it is better to always create a new branch off the develop branch. That way only commits pertaining to that branch are visble. Thanks

**Review by dave-ok — APPROVED** [review]

**Comment by ArinzeOkorji** [comment]
@dave-ok Yes, the `ft-reporter-dashboard` contains the navbar which is to be shared across the platform. Recreating it along with its tests, services, etc would have been a waste of time. However, I understand what you mean.

**Comment by dallintine** [comment]
are you using the firebase api to authenticate it or what

**Review by dallintine — APPROVED** [review]

**Comment by dallintine** [comment]
nice work

**Comment by dave-ok** [comment]
@dallintine I guess you closed this by mistake. Still waiting on reviewers so I am reopening it

**Review by johnebri — APPROVED** [review]

**Comment by ArinzeOkorji** [comment]
@dallintine It's a team effort

**Pull request merged**
