### PR TITLE
Feat: Added Angular framework

### PR DESCRIPTION
**Pull request by ArinzeOkorji**
## Description
Please include a summary of the change and relevant motivation and context.
- Added the Angular framework which would be used to develop the front-end application 

List any dependencies that are required for this change.
"dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-plugin-import": "^2.20.2",
    "prettier": "^2.0.5",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.23",
    "@angular/cli": "~8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes No issues stated yet

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dallintine** [comment]
"dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-plugin-import": "^2.20.2",
    "prettier": "^2.0.5",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
}





5:46
it is a bit higher than the one @Arinze push on the repo for a change what do we do should i follow @Arinze own or my will be better

**Comment by dave-ok** [comment]
@dallintine what you have installed locally is angular 9. Maybe we should stick with angular 8 as angular 9 is a very recent release. 

Also you don't need to install angular on your end. Wait till @ArinzeOkorji has finished setting up angular and this setup is reviewed and approved, then this pull request (PR) will be merged to the develop branch so that we have a unified starter codebase.
 
If you haven't cloned the repo, you can just clone the repo, run `git checkout develop` and you are good to go. But if you have already cloned this repo, ideally just delete it and repeat the steps mentioned above, since you have not done anything locally yet.
 
When we do start working and you need to sync your local repo with the source repo, you will need to run a `git fetch upstream` to fetch latest changes from the source repo (I am assuming you have setup a remote called upstream). Then `git checkout develop` to switch to the develop branch. Then run `git merge upstream/develop` to merge changes on the source `develop` branch with your local `develop` branch. ... I think it might be good to outline our git workflow steps on slack

**Comment by dave-ok** [comment]
@ArinzeOkorji Great job so far! I will like to point out though that these dependencies should be devDependencies. So you can just run `npm install --save-dev eslint eslint-config-airbnb-base ..........` to have them switched to devdependencies. It won't trigger a new download.
"eslint": "^6.8.0",
"eslint-config-airbnb-base": "^14.1.0",
"eslint-plugin-import": "^2.20.2",
"prettier": "^2.0.5",

And please also install as devdependencies I completely forgot about them: `eslint-config-prettier eslint-plugin-prettier`, for prettier. I am assuming you are using VS code so install the ESLint extension and ensure it is enabled and you the following setting:
`"editor.codeActionsOnSave":  {
       "source.fixAll.eslint": true
}`

**Comment by dave-ok** [comment]
@ArinzeOkorji we may experience a couple of issues with airbnb's linting rules because it was designed for JS projects while this is a typescript project.

Please checkout the following article for how to setup eslint and prettier for typescript. You have already done some part, ignore all the sections about installing plugins for `react` and `jsx` or anything involving react in `.eslintrc.js`. Also you may ignore the part about setting up `husky` and `lint-staged`:
https://www.robertcooper.me/using-eslint-and-prettier-in-a-typescript-project

Then install the following config to enable Airbnb support for angular. Follow the instructions on the repo to set it up:
https://github.com/efoken/eslint-config-airbnb-angular

If you have any questions please reach out. Thanks

**Review by ifeLight — COMMENTED** [review]
Have u run the app to see it's working

**Review by ifeLight — APPROVED** [review]
It has finally passed the test so we move on to the next thing

**Review by dave-ok — APPROVED** [review]

**Pull request closed without merging**
